import SwiftUI
import AppKit

/// Per-release notes for Qnet. Add new entries at the TOP of `entries`
/// — the changelog window renders newest first.
///
/// Convention: the topmost entry uses `timestamp: nil` to mark itself as
/// "the in-development entry" — the bullets being accumulated for the
/// next release. For that entry, both the version label and the build
/// timestamp displayed in the changelog window are pulled live from
/// AppVersion.swift, so they always match the running binary regardless
/// of how many patches have been bumped since the entry was started.
/// The `version` field on a current entry is therefore informational
/// (a hint of when the bullet collection began) and not displayed.
///
/// When you ship a release, freeze the topmost entry by filling in its
/// `timestamp:` with the actual build identifier and setting `version:`
/// to the actual final version, then add a new entry above it with
/// `timestamp: nil` for the next development cycle.
enum Changelog {

    struct Entry: Identifiable {
        let id = UUID()
        /// Major.minor.patch (e.g. "0.90.01"). The full identifier shown
        /// in the changelog window is this version concatenated with the
        /// AppVersion build timestamp for the *current* binary, or with
        /// a stored historical timestamp if you choose to lock one in
        /// per release.
        let version: String
        /// Optional historical timestamp. If nil, the live build's
        /// AppVersion.buildTimestamp is appended (only valid for the
        /// topmost / current entry). Past releases should set this so
        /// older entries don't drift when you rebuild today.
        let timestamp: String?
        /// Free-form bullet list rendered as one bullet per element.
        /// Use plain prose; markdown is not parsed here.
        let notes: [String]
    }

    static let entries: [Entry] = [
        Entry(
            version: "0.90.02",
            timestamp: nil,  // uses current AppVersion.buildTimestamp
            notes: [
                "Four methods now ship a C engine beside the Python one, and Settings \u{25B8} Solvers \u{25B8} Solver Engine chooses between them: Regenerative Monte Carlo, Exact Matrix-Analytic QBD, Adaptive Truncated CTMC and Exact Sparse CTMC. Measured on this machine, the C engines run 252\u{00D7}, 16\u{00D7}, 21\u{00D7} and 78\u{00D7} faster respectively. Python remains selectable and remains the reference: it is the readable statement of each algorithm, it needs no compiler, and it is what to reach for when a result looks wrong.",
                "The two engines are not two algorithms, and the app is built so that you can check that rather than take it on trust. Each C engine reproduces its Python counterpart's arithmetic operation by operation \u{2014} the same exact summation where the Python uses it, the same iteration order, and no fused multiply-add \u{2014} and each ships a parity test that runs both on every packaged example, on a sweep of model sizes, and on one malformed document per validation rule, then compares the output. For the QBD and the finite CTMC the output is identical byte for byte with no exceptions. The regenerative simulator goes further than it needs to: its C engine draws CPython's own Mersenne Twister stream, so both engines visit the same events in the same order and report the same cycles and the same estimates.",
                "Two departures from that, both measured and both stated where they apply rather than buried. In the regenerative simulator's 17-digit machine records the confidence-interval bounds agree to about 1e-12 rather than exactly, because CPython ships its own lgamma and the Student-t quantile's bisection amplifies a 1.6e-15 difference; it does not reach the six decimals the report prints. And a simulation stopped by its wall-clock safeguard stops at a different cycle in each engine, because one of them is 250 times faster \u{2014} the safeguard working at two speeds, not a disagreement about the method.",
                "If the selected engine is not installed \u{2014} a source checkout that has not run build_all_algorithms.sh, say \u{2014} the other one runs and the Status pane says so. A missing binary never turns into a method you cannot run.",
                "Every Settings pane now has Save, Cancel and Reset to Defaults. Settings are applied as you change them, as they always have been, so Save writes them to disk immediately and confirms with a green tick; Reset to Defaults confirms the same way; Cancel closes the window. The buttons do not move as the confirmation appears and disappears.",
                "Run \u{25B8} Exact Matrix-Analytic QBD prints a report. It was the last method whose entire visible output was its parser contract \u{2014} seventeen key=value records at seventeen significant digits, with the model name percent-encoded as value=M%2FM%2F1, and no heading, no table and no units anywhere in it. It now prints what the other methods print: a title, the model layer, the evidence class, a one-line run summary, and three aligned tables carrying queue length and drift, the tail probabilities and the numerical diagnostics \u{2014} residuals in scientific notation and the spectral-radius certificate beside them. The records are still written, unchanged, because the result parser and the CSV export read them; they are simply no longer what a reader is shown.",
                "Stopping a run is a cancellation, not a failure. Run ▸ Stop escalates SIGINT to SIGTERM to SIGKILL and the wrapper reports whichever signal won the race, but the verdict was read back off that exit status against a whitelist of two codes — so a stop that ended on 129 was announced as \"Monte Carlo failed (exit 129)\" in red beside the \"cancelled\" line it had already printed, and filed a red-X, zero-measurement record. The verdict now comes from the app's own record that Stop was pressed for that run, so every code the escalation can end on is covered; a run that had already exited 0 when Stop was pressed still keeps its completed result. A stopped run leaves the one \"cancelled\" line in the Status pane and no result entry at all — a run you called off is not a measurement — while a solver that fails on its own still reports its exit status, its stderr and a Failed record exactly as before.",
                "Edit ▸ Undo names the typing while you are typing in Settings. The item resolves its title, its enablement and its action from the focused text field's own undo manager, which is live AppKit state that publishes nothing, so the menu was only ever as fresh as the last change to something the app observes. Typing into a node name or the Status pane's search box happened to publish; typing into any numeric Settings field or the AI pane's API-key field did not — so Edit ▸ Undo went on reading \"Undo Change Buffer Mode\" while ⌘Z took back the digit you had just typed, and with an empty canvas stack it sat greyed out while the field had a whole word to give back, swallowing the first ⌘Z entirely. The focused field's undo state is now part of what the menu bar watches, so the item says what the next ⌘Z will actually do, from the first character on.",
                "Solver timing lines keep their spacing at every precision setting. The last place the display filter still treated prose as a table column was a line carrying exactly one number one space behind its label: at Settings ▸ Output Format ▸ Decimal places of 0, 1 or 2 the Linear Program's own timings arrived as \"[Parse]     0 s\" — the value shrank, and the filter widened the gap to hold the column it thought it was preserving. A lone number standing one space behind its label is now prose and keeps the spacing the solver printed, while a genuine printf column — the Moments table's %12.6f fields, the covariance and reflection matrices, the comparison table — is still held to its original width and keeps its decimal points stacked.",
                "Stop now stops the solver. Run ▸ Stop Run signalled only the wrapper shell that launched the work, so the solver itself — a Monte Carlo run at seventeen cores, say — kept going to its natural end while the app had already retired the run. The run's process group is recorded while the wrapper is alive and the escalation is sent to that group, and a cancelled run is no longer retired merely because the wrapper's completion file appeared; measured, the solver is gone about two seconds after the click instead of ninety.",
                "Edit ▸ Undo and Redo now describe the step they will actually take. Title, enablement and action are resolved from one routing decision, so the menu can no longer read \"Undo Add Station\" while ⌘Z is swallowed by a text field that has nothing to undo. And clicking the canvas takes keyboard focus back from a text field that still holds it, so one ⌘Z after typing in the Status pane's search box reaches the canvas rather than draining the search box first.",
                "Align and Distribute reached the menu bar. Network ▸ Arrange carries all eight commands — align left, horizontal centres, right, top, vertical centres, bottom, and distribute horizontally or vertically — greyed at the same thresholds the commands themselves use (two nodes to align, three to distribute), and the two centre alignments are new. The node context menu lists the same eight under the same names.",
                "Run ▸ Run SRBM MLMC produces its results again. Its output aggregator is an awk program, and one line of it wrote a bare ternary inside a printf argument list — which the awk macOS ships parses as an output redirection, so the program died at parse time and every MLMC run lost its whole queue-length table and its status record while printing three parser errors. The condition is parenthesised, and the run now prints the per-station block, the replication provenance and QNET_MLMC_STATUS_V1 as it always meant to.",
                "A run that fails now says so in the Status pane. A non-zero exit was recorded on the Results record and in the status bar, but nothing reached the Status log, so a solver that died mid-run read as one still in progress — which is how the MLMC defect above survived several rounds of review. Stopping a run is still not a failure and is not reported as one.",
                "The Shell no longer rewrites a comparison table's own cell into a different notation. At the exact magnitude where a rounded value lands on the scientific/fixed threshold — 9.999996e-07 printed as `1.00000e-06` at six decimals, or 999999999.9999 printed as `1000000000.000` at three — the terminal filter re-read the printed token, put it on the other side of the threshold and switched notation, so one pane showed `1.00000e-06` and the other `0.000001` for the same number. The two formatters now agree at the boundary as well as everywhere else; verified over 32,011 values at every setting from 0 to 9 decimals.",
                "Undo and Redo work again. Edit ▸ Undo and ⌘Z decided whether a text field had claimed the keystroke from NSApp.sendAction's return value, which is true whenever any responder claims undo: — so the canvas undo stack was never reached and Delete Selection and Clear Canvas could not be taken back. They now route on keyboard focus, and a focused text field still undoes its own typing.",
                "The Edit menu names the step: Undo Insert Tandem Line, Redo Delete Selection, rather than a bare Undo, so ⌘Z says what it will cost before you press it — and a redo now logs \"Redid: …\" in the Status pane instead of calling itself an undo.",
                "The node and link parameter editors are movable windows, not pinned sheets. Double-clicking a station opens a Node Parameters window that can be dragged aside so the station stays visible, resizes inside its band, and retargets in place when you double-click a second node — asking to save a dirty draft first, as its Cancel already did, on the title-bar button and ⌘W as well.",
                "The Settings window can be resized. It opened at one fixed size, which clipped the Discrete-Event Simulation pane's Run Length section, and the size it is left at is now remembered along with its position.",
                "A link out of a sink is refused where it used to be drawn. A sink is where jobs leave the network and every exporter ignores an arc leaving one, so the Link tool now says so instead of silently creating a link that the canvas counts and the solvers do not see; a chain that reaches a sink ends there. A document that already carries such a link — saved by an earlier build, hand-edited or imported — is reported by the Warnings pill and by Network ▸ Analyze Network rather than being solved as a different network than the one drawn.",
                "Double-clicking empty canvas reaches the hand again after a marquee selection or Select All. Both committed the Pointer tool without going through the tool switch, which left the sticky-pan memo standing and made every later double-click a no-op; the memo, the pending link start and the pending link point are now cleared on the one path, and the tool is single-writer so no call site can bypass it again.",
                "The empty canvas's \"Start from an Archetype…\" button, File ▸ New from Archetype… and Network ▸ Insert Archetype… stay live while the gallery is open, and a second request brings the gallery forward instead of doing nothing. The gallery is a movable window meant to be worked beside, so pressing the button again while it is up is exactly what a user does.",
                "An archetype insert fits the canvas to what it inserted. The fit was requested on a SwiftUI body that is not re-evaluated on every document change, so the network appeared off the right edge of the viewport at whatever zoom was in force; it is now consumed where the scroll view can always see it.",
                "The archetype gallery's thumbnails draw each network in the canvas's own vocabulary — a green diamond source, buffer rectangles open on their inflow side, blue station circles, a dark-red sink — instead of accent-coloured dots, and the gallery's empty-canvas footer names the buffer regime the insert will establish. A tile's VoiceOver default action now highlights it, with Insert as a separate action, so the knobs can be reached before anything is inserted.",
                "A detached pane's window is titled with its document: \"Untitled — Shell\" rather than a second item called \"Shell\" beside the Shell actions submenu in the Window menu. A window frame remembered from a display that is no longer attached is clamped onto the one screen it mostly covers, rather than into the union of every screen, which for two displays of different heights contains dead space belonging to neither.",
                "Every method's numbers now reach the Shell at the precision Settings ▸ Output Format asks for — including Exact Matrix-Analytic QBD, whose entire visible output is machine sentinel records, and Regenerative Monte Carlo, which prints five of them under a heading of its own. Those records used to be passed through untouched, so QBD showed `estimate=1.9999999999722793` at every setting and regenerative showed the same quantity twice on one screen, at two precisions. Only the value of a named float-bearing key is rewritten — estimate, standard_error, ci_confidence, ci_low, ci_high, ci_half_width, effective_cycles, and the QBD evidence rates and residuals — so a measurement that happens to land on a whole number (`estimate=1`, `value=1`) is shown at the configured precision like its neighbours instead of keeping the solver's bare spelling; the record head, every key, every integer field (level, iterations, cap_hits, exit) and every percent-encoded name are byte-identical, and the archived run output the result parser and the CSV export read still holds every digit the solver printed.",
                "Solver prose is no longer re-spaced. A number introduced by `=`, `:` or `,` keeps the spacing the solver printed, so `generator residual = 4.11409e-13` stops arriving with up to eleven inserted spaces at the shipped default, and `[0.883687, 1.081991]` is no longer pulled apart. Prose stays prose to the end of the line, so the second half of a pair keeps its spacing too — the Linear Program's `drift = -1.000 0.000` and regenerative's `effective cycles 1355.90` are no longer padded either. Genuine printf columns are still held to their original width, so tables keep their decimal points stacked.",
                "The Shell and the Results pane agree on notation. A value a solver printed in scientific notation is now displayed fixed or scientific according to its magnitude, exactly as the comparison tables and the Swift-rendered panes already decided it — so the Linear Program's `Optimal u* = 0.0000000000e+00` reads `0.000000` in the Shell instead of `0.00000e+00`. A token that arrived scientific and stays scientific still never gains mantissa digits.",
                "Run ▸ Whitt QNA, Whitt–You RQNA and the BNA-SRBM methods now refuse a network whose traffic equations have no finite solution, naming the station and the class, instead of exporting a fabricated arrival rate and letting the solver print a full table of `nan`. The flag bar and the ρ badges already refused it; the Run menu now says the same thing.",
                "Insert Archetype opens on infinite buffers when the canvas is empty. The gallery's own descriptions promise the exact Jackson branch, but a brand-new document defaults to finite buffers and adopted that choice, so the shortest path from a blank page to a runnable network produced one with all twelve infinite-buffer methods greyed out. A document that already holds stations still opens on its own regime.",
                "A network can start from a shape instead of an empty canvas. File ▸ New from Archetype… (⌥⌘N) and Network ▸ Insert Archetype… open a gallery of five starting networks — an M/M/c station, a tandem line, a fork, a rework loop and a re-entrant pair — each built at the number of stations, servers, arrival rate and utilisation you ask for, with the service rates back-solved from the traffic equations so every station really does land at the ρ you typed. The insert lands clear to the right of whatever is already on the canvas, names its nodes in the existing sequence, and is one undoable step.",
                "The empty canvas now offers the two shortest routes out of a blank page: \"Start from an Archetype…\" opens the archetype gallery and \"Open an Example…\" opens the bundled literature networks. Both perform their own menu item rather than keeping a second copy of the command, so a network is three clicks from a launched app.",
                "Canvas gestures answer where they used to go quiet. In the Link tool, dragging out of a station and back onto it draws the self-loop that clicking it twice already drew, and a source, buffer or sink says why it cannot have one instead of cancelling in silence; a drag that wobbles without leaving its node is honoured as the click it was. A double-click on empty canvas reaches sticky pan in the Multi-Select tool as well as the Pointer — a rubber-band with no area is a click, and is no longer committed as a selection. And with a node tool active, the second click of a double-click is suppressed by where the node would land rather than by how far the pointer moved, so a shaky trackpad double-click can no longer stack a second, invisible node on the first.",
                "With nothing selected, the arrow keys scroll the canvas one wheel line (⇧ = four) instead of doing nothing at all; with a selection they still nudge it by a whole grid cell.",
                "The Shell workspace preset now moves the divider it promises: the shell row takes 45 % of the window height, and Analyze Results gives the Results workspace half. A saved divider position used to be restored straight over both, so the preset appeared to do nothing.",
                "One-time repair for anyone carrying the old auto-reveal’s state: an earlier version reopened the Results workspace on every solver run and left it open, which reduced the canvas and the Shell to what was left of the window. It is closed once, only when the Shell is showing (the run is visible there), and the status log says so. No run record is touched; View ▸ Panes ▸ Results (⌥⌘6) brings it back.",
                "Maximize Pane (⌃⌘↩) acts on the canvas when nothing else has keyboard focus, instead of being dimmed at launch, and the canvas status bar carries the same maximize / restore control every other pane header has — so a maximize remembered across a relaunch is visible on screen.",
                "Two more dialogs became real windows. The archetype gallery (File ▸ New from Archetype…) is a movable, resizable panel, so the canvas it promises to insert “clear to the right of what is already there” stays visible while you choose; and a station’s picture picker is one too, from the docked Inspector and from the ⌘I sheet alike. Settings opens straight into the frame it was left at instead of appearing centred and jumping, and the About panel returns to where it was dragged — at its own fixed size, which is a lock rather than a preference.",
                "Delete removes a selected link. ⌫ with a link selected used to do nothing, and the undo step is now named for what actually went — Delete Link, Delete Node or Delete Selection. A station may also link to itself now: a rework loop that repeats a station’s own service is a real network, and only sources, sinks and buffers still refuse (each says why). Clear Canvas keeps the promise its alert makes — one Undo brings the network back, numbering included.",
                "A network is born at a useful load. A station placed by hand is served at μ = 1.1111111 against the default source rate of λ = 1, so the first chain anyone builds sits at ρ = 0.900 instead of exactly 1.000 — the boundary of instability, where the analysis used to short-circuit to \"unstable\" and paint every ρ in red. Sources arrive Poisson, the way every bundled example spells them. The status line says the number rather than merely applying it. The flag bar now follows the build: adding a node, drawing a link, deleting a selection, clearing the canvas and inserting a template all invalidate the analysis and re-run it quietly, where before only a parameter edit did, so the Analytical, Re-entrant and Warnings pills could describe a network that no longer existed for a whole session. Dragging nodes does not re-run it — layout is not an input to any of them. Inserting a template into a canvas that already has a source now moves the inserted links onto the customer class its own source actually owns, instead of leaving a second class with no routing at all, and an insert never re-interprets the buffer regime of the stations already on the canvas. The template gallery draws each network it offers.",
                "Two networks side by side are still exactly solvable. Inserting a second archetype gives the document a second customer class, and the tractability detector used to demote any such document from the exact Jackson branch to the GCDG asymptotic branch purely on the class count — with the asymptotic branch switched off it reported no closed form at all. A document whose classes share no station is not a multi-class network; it is that many independent Jackson networks drawn on one canvas, and it is now recognised as one. The bundled Schwerer01.d3.c3 example — three independent M/M/1 queues at ρ = 0.45, 0.40 and 0.42 — is the case in point: it now reports the exact E[N] of 0.8182, 0.6667 and 0.7241 instead of an approximation of them. A station that two classes genuinely share is still refused, and the gallery footer now says which of the two an insert gives you.",
                "A routing loop that no job can leave is refused instead of being answered. If every job leaving a station comes straight back to it — one self-loop at probability 1.0 is enough, and the Link tool has always allowed it — the traffic equations have no finite solution and the station is unbounded, not merely busy. Qnet used to hand back the external arrival rate as though it were the solved throughput, so a network that cannot be stable was reported at ρ = 0.900 with an \"exact\" mean queue length of 9.0 beside it. It now names the station, says why its throughput is unbounded, and the ρ badges stay empty rather than showing a number nothing computed.",
                "The canvas draws links the way every diagram editor does: with the Link tool, press on a node and drag to another one — a dashed line in the chain’s class colour follows the pointer, and over a candidate it becomes the exact arrow the release would create. The two-click flow shows the same preview between its clicks, and both run one implementation, so class selection, the refusal to repeat a pair and chain continuation behave identically whichever way the link is drawn.",
                "A double-click on empty canvas hands the canvas to the hand — the pointer becomes an open hand and dragging pans — and the next single click gives the previous tool back; H, the Tools palette and the Space bar are unaffected. With a node tool active, a fast double-click now places exactly one node instead of stacking a second, invisible one on the same grid point. The empty canvas itself gained a working \"Open an Example…\" button, and now states the rule a first network breaks: a station is served through exactly one buffer. The fifty literature networks ship inside Qnet.app and are found there first, so that button opens on them rather than on wherever you happened to be last, whatever directory the app was launched from. The pane corner-resize grips follow the Results pane: each T-junction sits on the divider that actually crosses there, and dragging one moves only the two dividers that meet at it.",
                "The self-loop is now as visible as every other link while it is being drawn. Dragging out of a station and back onto it — or, in the two-click flow, moving off the pending start and back — shows the loop arc the release would leave behind, nested outside any loop the station already carries, instead of a dashed line running back into the node it came from. On a source, buffer or sink, which cannot have one, the band promises nothing and the click still says why.",
                "Escape puts a drag back. Pressing it while nodes, a link or a link being drawn is in flight returns everything to where the drag started, drops the alignment guides, and leaves no undo step behind — the group is closed, not committed — and the release that follows commits nothing and is not read as a click either. With nothing being dragged, Escape still means Deselect All. An ⌥-drag is the one exception: it has already made the copies it is carrying, so Escape keeps its other meaning there rather than stacking an invisible node on every original.",
                "Any pane can take the whole window: the maximize button in a pane header, or View ▸ Panes ▸ Maximize Pane (⌃⌘↩) on the focused pane. Nothing is hidden — restoring puts every divider back exactly where it was.",
                "Any pane can also leave the window entirely. View ▸ Panes ▸ Separate Windows — or the toolbar's Workspace menu — gives the Status, Inspector, Results, Shell or AI Assistant pane a window of its own, at its own size and position, remembered for the next launch. The main window's layout closes over the gap, and the pane keeps working exactly as it did: the Shell keeps its process and its scrollback, the Results workspace still follows the front tab, and ⌘F, ⌥⌘= and Window ▸ Focus still act on it. Closing the window puts the pane back, and so does the button at the end of its header; Return All Panes to the Main Window, in the same menu, brings back every one.",
                "Window ▸ Focus (⌃⌘0–6) now shows the pane it focuses in every case. With another pane maximized it used to switch a pane on that nothing was drawing, and move focus nowhere.",
                "The first solver run no longer forces the Results workspace open forever. It reveals it once, and only when the Shell is closed too, so a run that is already visible somewhere does not letterbox the canvas.",
                "A new install starts with five panes rather than six: the AI Assistant is off until you ask for it (⌥⌘4).",
                "A Shell workspace preset, and the preset list one click away in the toolbar’s Workspace menu rather than three levels down a menu.",
                "The Shell behaves like a terminal. ⌘F opens its own find bar over the scrollback instead of the canvas’s Find Node prompt, ⌘G and ⇧⌘G walk the matches, ⌘C copies the shell selection — SwiftTerm’s view is not a text field, so Edit ▸ Copy could not see a selection there at all — and a right-click offers Copy, Paste, Select All, Find in Shell…, Scroll to Bottom and Clear Shell, with the same titles those commands carry in the pane header and in Window ▸ Shell. The find bar sits inside the pane rather than against its edge: it used to be pinned to the terminal, which runs off to the right once wide output has made the Shell scrollable, so its close button and its Aa / .* / Word toggles were the first things the pane clipped away.",
                "Wide solver output no longer wraps into an unreadable zig-zag. Qnet measures the width of the lines the shell prints, straight off the byte stream and ignoring colour codes, progress-bar redraws and the shell’s own prompt sequences, so a comparison table wider than the pane keeps every row on one line and offers the horizontal scroller instead. Clearing the Shell retracts it again, and changing the shell font re-computes it.",
                "A solver run is typed into the interactive shell, so Qnet now checks that the shell is free before typing. A half-typed command line is discarded rather than concatenated into the launch, and a run is refused outright — with the reason in the Status pane and the status bar back at Idle — when a full-screen program such as vim or less owns the screen, when a command such as cat is reading the keyboard, or when the Shell pane has not been opened yet, which used to surface a minute later as a bare “exit -1”.",
                "Auxiliary windows stay where you put them. Qnet Help, the Network Model guide, Release Notes, the Method Chooser and the Settings window all remember their frame across a quit, open into a full-screen space instead of pulling you out of it, and the Network Model guide is no longer torn down and rebuilt every time it is opened — which is what used to move it back to the centre. Canvas Export Options is a real, movable window rather than a sheet, so the diagram it is about stays visible behind it.",
                "Every remaining parameter dialog became a movable window too. Find Node, Generate Random Network, Run Test Set, Run Spectral Convergence and the run-parameter form the seven configurable solvers share were the last five sheets: each opens now as a real window you can drag aside, resize and leave standing while you read the canvas, the Shell or the Status pane it is about. They still belong to the document window, still travel with it, and still take Escape as Cancel, so nothing you could do before is gone — and Find Node now follows the canvas while it is open rather than searching the node list as it stood when you opened it. The one dialog that is still a sheet is the startup dependency check, which is meant to block launch.",
                "The About panel and the wide popovers stop clipping at Accessibility text sizes: their content scrolls and their titles wrap instead of being cut off at one line.",
                "Settings ▸ Output Format ▸ Output decimals now governs every method, not the twelve that happened to print through the comparison formatter. Every decimal number a solver writes is normalized on its way to the Interactive Shell, so one session can no longer show 0.66666667, 4.0000000000000018, 4.0000 and 4.000 for the same class of quantity. Whole numbers stay whole — station indices, cycle counts, caps, seeds and exit codes never gain a decimal point — a value too small to show at the chosen precision falls back to scientific rather than printing a flat 0.000 and one too large stays scientific rather than expanding into twenty digits of floating-point noise, a number the solver already wrote in scientific notation never gains mantissa digits it never computed, an explicit + sign survives, and the progress bars and spinners still animate. Every row of a printf-aligned column still starts in the same place as every other row of that column at every setting, and a column that grows when you ask for more decimals now takes the room out of the gap its own solver left rather than pushing every column to its right out from under its heading. A number written in scientific notation is normalized to one spelling, so a line carrying both 1e-9 and 6.02e23 no longer prints them two different ways, and the number that ends a sentence is rounded like the rest of its line instead of being the one value left at the solver's own precision. Numbers are normalized only where they are results: the Analyze Network and Network Primitives reports and the Help pages keep their own prose and their own thresholds. The setting is a display preference: the run output Qnet parses, stores and exports keeps every digit the solver printed, and a solver that pauses in the middle of writing a number can no longer have its two halves formatted separately.",
                "A solver's first line of output no longer lands in the middle of its own progress line. Eight of the twenty-two methods — exact open product form, matrix-analytic QBD, the truncated and generic exact CTMCs, regenerative Monte Carlo, both BAR methods and finite-buffer decomposition — printed straight onto the line their spinner was still redrawing, so the Shell showed a \"Solving …\" progress line welded to the solver's own title, then the results, then a second, stranded \"[done]\" line underneath them. The spinner now owns its line until the run ends and the output follows it, which also stops a long solve's output being sliced in half by a redraw.",
                "Qnet no longer stops everything to tell you a run did not start. Seventy-four failures — a solver binary that is not installed, a network a method does not apply to, a temp file that could not be written — used to raise a modal alert with a generic folder icon and a single OK button and write the same sentence to the Status pane on the same path. They now go to the Status pane only, where the alert's own text (the solver search trail, the exporter's diagnosis of which station is unfed) is kept under the summary instead of disappearing when the alert was dismissed, and a hidden Status pane opens itself rather than swallowing the report. Save and Load keep their alerts: a write that silently did not happen is the one failure you have to be told about.",
                "\"Open an Example…\" says so when it cannot find the examples. A bundle without them used to open a file panel on wherever you were last, showing nothing and explaining nothing; it now names the directories it looked in, in the Status pane and on the panel itself.",
                "The Exact Result column no longer invents digits. It had been computed at six decimal places whatever the setting said, so asking for nine printed six real digits followed by three zeros beside algorithm columns that were honestly rounded. The same fix reaches the Monte Carlo and Linear Program queue-length columns, which silently read zero for a station whose effective service rate fell below 1e-10.",
                "The error bar a Monte Carlo run computes is printed again. Every simulation column of a comparison or single-method table now reads \"value ± half-width\" at the chosen precision — the half-widths were parsed and then silently discarded, so a fifty-replication simulation printed a bare number with a percentage beside it. Only the columns that reported one get a ±: an analytical method is never given a fabricated interval. The Results pane and CSV export follow, showing a 95 % interval where they used to show a dash, and a simulator's half-width is no longer recorded under the name \"standard error\" — it is the interval it describes, sorts by the width of that interval, and exports in its own half_width column. The infinite-buffer simulator's interval is now a Student-t interval at the replication count it actually ran, as the finite-buffer one already was: at ten replications the half-width it printed as 95 % was 13 % too narrow to be one.",
                "The Results pane reads the same number as the terminal it was parsed from: estimates, interval bounds, standard errors and residuals all follow Output decimals instead of showing seven significant digits of their own. Numeric columns are right-aligned in monospaced digits so magnitudes can be compared straight down a column, their headings sit over them, and a cell too narrow for its value now truncates at the end — a middle-truncated 0.81…457 read as a real number. Derived model readouts in the inspectors are unchanged, and CSV export stays at full precision.",
                "Qnet now opens with a live startup checklist that checks each runtime package in order, marks ready items with green checkmarks, and keeps the current and just-checked package visible. Missing items produce one copyable, de-duplicated Homebrew command; optional Python and experimental-method dependencies are labelled as optional. A packaged app verifies its bundled native solver components instead of falsely requiring a local Homebrew cellar, while a source-tree run checks the actual developer formulae needed to rebuild them.",
                "The docked Inspector no longer snaps back to Class 1 after a commit: a document change under the pane refreshes the field text but keeps the class being edited and the entry mode. Undo and redo keep the canvas selection, so ⌘Z after a pane edit shows the restored value in the same field, and an undone field run never continues. Escape in the pane reverts an uncommitted draft; an invalid edit dropped by moving the selection is now logged (\"Discarded invalid edit to S1: Servers (\"abc\")\"). The Load readout stacks λ / c·μ / ρ in the pane so a four-digit rate never truncates; class rows in the ⌘I sheet are no longer Tab stops and ↑ / ↓ inside a field stay with the field. The SRBM export sheet's \"Throughput Γ\" row, which described nothing in the file, is gone — the file's Γ is the covariance matrix and now has its own glossary; the throughput Γ is explained where it is shown, in the Analytical popover's per-station table. Help gained an Editing Parameters page (pane vs. sheet, commit rules, shortcuts); View ▸ Panes ▸ Inspector has a tooltip and Show All Panes counts it.",
                "Closing a tab with unsaved changes asks Save / Don't Save / Cancel — from the tab's close button, a middle-click, the tab's context menu (Close Tab, Close Other Tabs, Close Tabs to the Right), File ▸ Close Tab (⌘W) and Close All Tabs (⌥⌘W) alike, one question per dirty tab the way Xcode reviews them. Save writes the file, or asks where for an untitled network; Cancel keeps every tab. Window ▸ Reopen Closed Tab (⇧⌘T, Safari's key) brings back the last tab closed this session, log and all — a tab closed with Don't Save comes back with its unsaved changes.",
                "Window ▸ Focus uses the same digits as View ▸ Panes: ⌃⌘1 Tools, ⌃⌘2 Status, ⌃⌘3 Shell, ⌃⌘4 AI Assistant, ⌃⌘5 Inspector, and ⌃⌘0 for the canvas, which has no pane to show or hide (Focus Canvas was ⌃⌘1 and Focus Tools ⌃⌘6). Show All Panes now includes the Inspector, whose View ▸ Panes item gained the same tooltip as its siblings.",
                "Every tooltip that cites a key reads it from one table (Help ▸ Keyboard Shortcuts' source), which the debug-build menu audit checks against the live menu bar — so a rebinding can no longer leave a tooltip teaching the old key, and the design lint rejects a bare ⌘<digit> typed anywhere else.",
                "The AI Assistant header tells the truth per tab: while a request runs for another tab the provider chip stays 'Ready', a 'Working on <network>' badge says where the work is, Stop says which request it stops, Clear stays available, and the message field explains that it is waiting for that request. The run_command tool refuses — naming both tabs — instead of running a solver on the wrong network when the conversation's tab is not in front.",
                "The Analytical / Re-entrant / Warnings pills moved under the Status pane's header, so the right column reads header-then-content like every other pane instead of the pills floating between the Inspector and the Status header. The column keeps one width whichever of the two panes shows, so toggling the Inspector no longer resizes it (or the AI pane beneath it) under the pointer.",
                "The Status pane's 'k of n' readout and Return / ⌘G stepping now belong to the search query alone; choosing a severity filter with an empty field no longer shows a match count for a query nobody typed.",
                "The Shell installs a 16-colour ANSI palette tuned for its ground — one for light, one for dark and the classic theme — so the bright yellow, green and cyan that ls and the solver banners print are legible on the light ground; its overlay scrollers fade with the design system's durations and stop with Reduce Motion.",
                "Increase Contrast now reaches every structural stroke, not only the design-system controls: message bubbles, code and tool-call cards, the per-class and routing tables, the canvas legend and zoom cluster, the ρ badge and the sheet glyph all step their borders and washes up with the switch, and the faintest label grey darkens with it the way the system's own labels do (measured 4.85 : 1 light and 5.09 : 1 dark, gated in validation/ds_contrast.swift under the high-contrast appearances). A release build now runs the design lint before compiling.",
                "Empty states follow one wording rule — a Title Case title ('No Status Entries', 'No Network Yet', 'No Results') over a sentence — across the canvas, Status, Inspector, AI and Help panes.",
                "The app icon's full-detail tier draws the buffer the way a queueing diagram does — three waiting jobs in a tight row in front of the station — and both arrowheads stop the same distance from their nodes; make_icon.sh measures both from the rendered pixels.",
                "A docked Inspector pane (View ▸ Panes ▸ Inspector, ⌥⌘5; focus with ⌃⌘5) sits above the Status pane and follows the canvas selection, so a node's parameters can be edited while the node, its neighbours and their utilisation badges stay in view. Every field commits when you leave it — Return, Tab or a click elsewhere — as an undoable step named for the node, and a run of edits to one field folds into one Undo, the way a held arrow key already did for a nudge. The ⌘I sheets remain as the review-and-save host of exactly the same sections (NodeInspectorSections / LinkInspectorSections bound to one draft model), with Previous / Next; they now open at one size for the whole sibling walk instead of resizing when a multi-class station follows a single-class one, and Cancel and Escape ask Save / Don't Save / Cancel on a dirty draft exactly as switching siblings does. A station's Capacity section shows a live λ / c·μ / ρ readout computed from the values being typed, warning at ρ ≥ 0.95 and calling ρ ≥ 1 unstable; the per-class table gained a λ column beside μ, one focusable row per class (↑ / ↓ move between rows, VoiceOver hears the row and its message by class name) and a caption slot of exact height. A Routing section in the node inspector lists the outgoing links with their per-class totals (and the incoming ones, dimmed), each opening the link inspector. Hovering a node on the canvas now says what λ, μ and SCV are, not just their values.",
                "Help ▸ Keyboard Shortcuts is a new help topic generated from the live menu bar: every key equivalent grouped by menu, a lead on the modifier conventions (⌥⌘ runs a method, ⌃⌘ moves focus, bare letters pick tools) and the canvas keys no menu prints. Read from the menus, so it cannot drift.",
                "⌘1–⌘9 now show the first nine document tabs, listed by title in the Window menu with a check on the front one — what those keys mean in every tabbed Mac app. Zoom to Fit and Zoom to Selection moved to Keynote's ⇧⌘0 and ⌥⇧⌘0, beside ⌘0 Actual Size.",
                "Run Linear Program and Run Multi-Class SRBM had no help page and opened a concepts page about the SRBM. Both have their own Method Reference topics now — what they compute, what every field in their sheets means, when to trust them — and Export All Solver Inputs opens a new Solver Input Files topic.",
                "Help ▸ Method Reference explains itself: every item's tooltip is the full topic title and the solver binary ('SBD — Sequential Bottleneck Decomposition (BNAsbd · bna_sbd)'), so the two 'Spectral Method' and two 'Simulation' entries are told apart. The topic is 'Finite-Buffer LP' everywhere.",
                "The run sheets' Help affordance is the Mac help control — the round '?' in the bottom-left corner — instead of a third push button. It is a slot on the shared sheet footer, so the SRBM export sheet and both Test-menu sheets link to their topics the same way.",
                "Print Diagram prints vector art. The print view draws the same PDF page File ▸ Export ▸ Diagram as PDF writes, so lines and labels stay crisp on paper and Save as PDF from the print panel yields vector rather than a 4× raster. File ▸ Page Setup… is back beside it.",
                "No command that changes the document or opens a panel is enabled while a sheet is up: Cut, Paste, Duplicate, Delete Selected Link, Clear Canvas…, Copy as Image, the diagram exports, Page Setup and Print dim, so ⌘D cannot duplicate the node under edit. Text fields keep Cut and Paste.",
                "Release Notes reads as release notes: every bullet in this entry is one user-visible change in plain prose, and the developer-only 'frozen entry' banner shows in debug builds alone.",
                "Qnet Help parses each topic once and caches the result, so typing in the search field no longer re-parses a twenty-kilobyte document several times per keystroke. View ▸ Panes items gained tooltips, and the toolbar's 'Straighten' button is titled 'Straighten Network' like its menu item.",
                "Design tokens live in one place: DS in DesignSystem.swift is the only home for a visual constant. Every window, pane and sheet dimension is a token, sheet geometry is one DSSheetSize band per kind, and DS.Symbol settles one SF Symbol per command — Zoom to Fit had shown two mirrored glyphs at once.",
                "Colour tokens are cached constants rather than computed properties, which stops the canvas allocating thousands of NSColors a second during a drag.",
                "Light-mode legible tint darkened from 42 % to 48 %: the green Tractable and orange Warnings pills measured 4.35:1 and 4.48:1 against their own wash and failed WCAG AA. validation/ds_contrast.swift now measures every text-on-colour pair in both appearances and the lint fails the build below 4.5:1.",
                "The design lint also rejects raw text styles, raw label colours, material chrome, frame literals and DS extensions outside DesignSystem.swift.",
                "Reduce Motion, Increase Contrast and Differentiate Without Colour are honoured throughout: DS.Motion returns no animation under Reduce Motion, borders step up under Increase Contrast, and the AI status dot and class swatches take a shape as well as a colour.",
                "Run Qnet --ds-gallery to see every token and component side by side in light, dark and the Accessibility 1 text size.",
                "The app icon is one identity at every size: the 16 and 32 px tiers are pixel-art reductions of the same source-station-sink diagram the large tiers draw, and make_icon.sh also emits dark and tinted appearance variants.",
                "The node inspector shows a per-class service table — one row per customer class served at the station, with a class chip, distribution menu, native parameters or mean and SCV, and live Mean / SCV / μ readouts.",
                "Bulk actions in that table name their own scope ('Copy C1 to 5 Other Classes', not 'to all classes') and offer a one-click revert afterwards, because Command-Z does nothing inside a modal sheet.",
                "Every derived number in both inspectors is printed at one precision (DS.Number.readoutDigits), so the table and the distribution card below it can no longer disagree about the same value.",
                "Both inspectors walk their siblings in place: Previous / Next (Option-Up / Option-Down) step through the stations in the exporters' order, asking to save first only when the draft is dirty, so checking five stations is one sheet rather than five.",
                "The link inspector lists the sibling links leaving the same node for the same class with their running probability total; each row opens that link in place, and Balance to 1 sets this link's probability to whatever the siblings leave over.",
                "Both inspectors commit every field as one undo step and log one summary line. Half-typed numbers no longer flash red, and neither does a cleared Name: 1e-3 and 0. can be typed character by character while the footer says 'Still typing …' and Save waits.",
                "An untouched Save is a true no-op on every node kind — including a multi-class station whose file stores a legacy Poisson default law, which previously registered an empty undo step and dirtied the document.",
                "Selecting a node or a link no longer writes a line to the Status pane; the status bar reports the selection, and the log stays a record of solver output and document changes.",
                "Links no longer run through stations they are not attached to. Every link is routed in world space against the other nodes: a clear chord stays straight, and a blocked one is bowed by exactly enough to step clear, on the side facing away from the drawing.",
                "Across the fifty shipped example networks the router took 95 arrows drawn through a third node down to none, checked by validation/canvas_perf/run_routing_check.sh, which fails on any crossing. Routes are planned once per layout, so panning a 200-node network still costs 0.3 ms a frame.",
                "Dragging a node shows alignment guides: within four points of a neighbour's edge or centre a hairline appears and the node snaps to it. Hold Control to place it freely, which suspends Snap to Grid and the guides at the same time.",
                "Arrow-key nudges coalesce, so holding an arrow for a second is one Undo Move Nodes instead of fifteen, and nudging a group with Snap to Grid on moves the whole group by the anchor's delta instead of collapsing it onto one cell.",
                "Links are reachable from the keyboard and VoiceOver: each is an accessibility element on its own arrow, spoken with its class, endpoints and routing probability, with Edit Parameters and Delete Link actions. Option-Tab walks the links attached to the selected node.",
                "The status bar counts a selected link instead of saying No selection while one is highlighted, so it is exactly the inverse of Edit ▸ Deselect All being available.",
                "Window ▸ Focus Canvas draws one accent rule, not two — the canvas and the tab bar had each grown their own — and all three panes share one implementation.",
                "The drawing can leave the app: File ▸ Export ▸ Diagram as PDF… writes vector art on a transparent ground for a paper figure, and Diagram as PNG… writes a 2× raster on the canvas ground for a slide.",
                "Edit ▸ Copy as Image (⌥⌘C) puts both a PDF and a TIFF on the clipboard so the diagram pastes as vector art into Keynote and Pages, and ⌘P prints the same render. All four render in the light appearance whatever the app is set to.",
                "Edit ▸ Deselect All (⌥⌘A) has one implementation behind Escape, the menu and the context menu. Option-drag duplicates and moves as a single undo step under the copy cursor, and the rubber-band selects a node whose body it touches, not just its centre.",
                "Tab and Shift-Tab walk the nodes in reading order and scroll the target into view. The hidden double-click Pointer / Pan toggle is gone; each cursor means one thing, and Zoom to Selection means the same in all four places it appears.",
                "Canvas context menus carry no key equivalents of their own — the menu bar owns them — and every title in them is copied from the menu bar verbatim.",
                "Every Run menu item explains itself: all twelve carry a one-line tooltip naming what the method computes and which solver binary runs it, and a dimmed item says why — an empty canvas, or a network in the other buffer mode.",
                "Run items that open a dialog take the HIG ellipsis: Run Monte Carlo…, Run Spectral Method…, Run Finite Element… and Run Multi-Class SRBM…. The ones that launch immediately (QNA, RQNA, SBD, Exact Simulation) stay bare, as does Run Comparison, whose prompt is optional.",
                "Run 'Finite LP' is now Run 'Finite-Buffer LP', the name Settings already used, and Run Multi-Class SRBM drops the '(Experimental)' suffix it repeated from the section heading directly above it.",
                "The terms the run sheets name — polynomial degree, mesh size, grid size n, basis size m, smoothness weight, warm-up, replications — gained glossary popovers behind the '?' beside each field.",
                "Menu commands that present a sheet, switch tabs or move pane focus are disabled while a sheet is up. A shortcut fired underneath an open sheet used to queue a second sheet that SwiftUI silently dropped, leaving the canvas tool letters and Delete dead until relaunch.",
                "Run Comparison no longer changes the default blocking regime behind your back: the choice is remembered only when 'Skip this dialog from now on' is ticked. Run Spectral Method likewise stopped writing the Legendre switch into Settings on every run — that is what Set as Default is for.",
                "File ▸ Save dims once the document matches the file on disk, like every other Mac document app, and says 'No unsaved changes' when it does. Close All Tabs, Close Window and Generate Random Network… gained the tooltips their neighbours already had.",
                "View ▸ Snap to Grid moved from ⇧⌘G to ⌥⌘G. ⇧⌘G is the system's Find Previous, which sits beside ⌘G Find Next in the Edit menu, and AppKit registers only one item per key equivalent.",
                "Qnet Help walks its search matches: selecting a topic scrolls to the first one, the breadcrumb bar shows 'i of n' with previous and next buttons, and Edit ▸ Find Next / Find Previous (⌘G / ⇧⌘G) step through them. The match under the cursor is tinted more strongly than the rest.",
                "Release Notes opens on the current release. Earlier versions are collapsed rows titled 'Version X — date' with Expand All in the top bar, so the window no longer opens onto fifteen thousand words of history. Copy copies the current release only, and says so.",
                "Clear Status Log is one command with one behaviour: the Edit menu item and the Status pane's trash button share an implementation, so both ask the same question above twenty entries.",
                "The second, unreachable help window is gone. Help ▸ Exact Simulation Guide goes through the same dispatch as every other topic, so it honours the Settings ▸ Help destination (Help window, Status pane or Shell).",
                "Window ▸ Focus Shell is ⌃⌘3, closing the gap in the ⌃⌘1 / 2 / 4 focus family and agreeing with View ▸ Panes ▸ Shell at ⌥⌘3. ⌃` still focuses the Shell.",
                "Shell actions moved out of View, where HIG reserves the menu for presentation: Clear Shell (⌘K), Find in Shell… and Restart Shell… are a Shell submenu of the Window menu, directly under Focus Shell.",
                "One name for the inspector command everywhere it appears: the Edit menu item, the node context menu and the link context menu all say 'Edit Parameters…' and all show ⌘I.",
                "The Exact Simulation guide is a full Qnet Help topic rather than a window with its own type scale and search: every word of it is searchable and highlighted like every other topic, and can be printed to the Status or Shell pane.",
                "The Help topic 'Interactive Shell' is titled 'Shell', matching the pane.",
                "Edit ▸ Search Settings… works from the mouse as well as the keyboard: the menu item posted a notification nothing observed, so only a hidden shortcut button in Settings ever handled ⌘F. There is now one path, the menu item.",
                "Settings no longer loses a value typed into a field and not tabbed out of: every numeric field commits as it goes away, and closing the window resigns first responder first.",
                "Settings search steps through every hit instead of landing on the first one for ever: the field shows the position (3 of 5), Return moves to the next match and wraps into the next pane, and every matching row keeps a quiet tint while the query stands.",
                "Settings search walks its matches exactly as the counter says: when a query switches to the first pane that has a hit, that hit is already flashed and the first Return moves to the second one (it used to re-flash the first). ⇧↩ (Shift-Return) steps back, mirroring Return, beside ⇧⌘G.",
                "Reset to Defaults (per pane, or Reset All Settings…) never shows or hides a pane: the AI Assistant pane's visibility is View ▸ Panes state like its siblings, and the confirmation says so. On the Linear Program panes, Reset now flashes the grid-size and basis-size fields whose values changed rather than the auto-scale switch above them.",
                "Importing a settings file names refused values the way the window does — 'Exact Simulation (MLMC) ▸ Path length T (outside 0.01…10,000)' instead of the storage key — and lists every one behind Show Details… when more than four are refused. Pop-up choices (blocking mode, LP backend, grid type, γ, the AI provider …) are checked against exactly the options the pane offers, so an imported value can never leave a menu blank. Exports carry the Qnet version that wrote them, and a file written by a newer settings format is refused with a clear message instead of applied in part.",
                "The Settings sidebar and the Help sidebar use the same SF Symbols as the run sheets — the die for Monte Carlo, the function sign for the spectral method, the grid for finite element, the checklist for test sets — so a solver wears one glyph wherever you meet it. The multi-line System prompt field ends at the same trailing edge as the fields above and below it.",
                "Jargon-only Settings labels carry a clickable question mark with a plain-language definition — utilisation ρ, target RMSE ε, the MLMC step factor γ, grid_n, basis_m, polynomial degree, mesh size, blocking mode, grid type, quadrature and the random-network topology — spoken by VoiceOver.",
                "The ρ ranges got the 0.05 stepper their signature had been accepting and dropping, and the MLMC thread count shows 'auto' with the core count instead of a literal 0.",
                "Every pop-up menu in Settings is the same row as every field, so labels, captions, tooltips and help buttons line up across the panes. The AI Assistant pane's four hand-styled controls became the shared icon menu, icon button and icon toggle, and its system prompt is a real multi-line field.",
                "Debug builds assert that no settings row can be searched for but not scrolled to, that no two rows share an anchor, and that Reset to Defaults is never keyed on a preference that does not exist.",
                "Bare-letter tool shortcuts (V M H · S B O X · L) and ⌫ are disabled under every sheet, including the ones the app scene presents (Generate Random Network, Find Node, Run Test Set, Run Spectral Convergence and the run-parameter sheets), so typing in a stepper cannot switch the canvas tool underneath.",
                "One confirmation idiom for destructive window-level actions: Clear Canvas, Restart Shell, Clear Conversation and the quit-time 'Restore tabs?' question share a helper that fixes the wording, the button order and the destructive styling.",
                "⌘Z / ⇧⌘Z undo typing inside any text field (node name, AI composer, Settings, help search) before falling back to the canvas undo stack, and Backspace typed in the Shell no longer deletes the selected node.",
                "The bare-letter tool hotkeys are disabled while Qnet Help, Settings, Release Notes, About or a sheet is the key window, so type-select in those lists never switches the canvas tool.",
                "The AI transcript renders Markdown tables as a real grid (semibold header, rule beneath, numeric columns right-aligned with monospaced digits, horizontal scrolling, Copy Table as TSV), and inline code spans use the code font the header font menu selects.",
                "Fenced code and tool-call input / result wells in the AI pane scroll in both directions inside their height cap and offer Show all N lines, so a long read_network result is never cut off. The backend chip and export menu take the same hover, pressed and disabled washes as the icon buttons.",
                "Status pane: ⌘F says Search Status Log… and puts the caret in the pane's search field while it has focus; the filter row shows 'N of M' whenever a filter or a query hides entries; clearing more than 20 entries asks first, and every clear can be undone from the empty state until the next one.",
                "Document tabs can be dragged into a new order, an accent bar marking where the tab will land, and the tab bar carries the same 2-pt focus rule the pane headers use so Window ▸ Focus Canvas (⌃⌘0) is visible.",
                "View ▸ Panes ▸ Increase / Decrease Pane Text Size dim when the focused pane cannot act on them or is already at its smallest or largest size, and the status bar reads 'Selected 3 nodes' / 'No selection' instead of a bare count.",
                "Qnet Help finished: search matches are highlighted in the page, Edit ▸ Search Help… (⌘F) focuses the sidebar search field while the Help window is key, the sidebar shows 'N topics match' while a query is active, and the plain-text destinations use the plain topic titles.",
                "All seven modal sheets — Node and Link inspectors, Export SRBM Solver Input, Generate Random Network, Find Node, Run Test Set and Run Spectral Convergence — share one chrome: 44-pt glyph header, grouped form with monospaced-digit fields, and a footer naming the first problem.",
                "The two Test-menu sheets validate live (min ≤ max, ρ inside (0, 1)) and the convergence sheet shows the number of spectral solves the sweep will run.",
                "Every run-parameter dialog is one of those sheets too. Run Monte Carlo, Run Spectral Method, Run Finite Element, Run Multi-Class SRBM, Run Linear Program, Run Comparison's blocking prompt and the blocking convention for Export ▸ All Solver Inputs were modal alerts with AppKit fields.",
                "Those dialogs use the shared sheet chrome: grouped sections (Model, Run Length, Performance), stepper-backed numeric fields that validate and clamp as you type, units in their own column, glossary popovers, Return to run and Escape to cancel. Solver command lines and output parsing are unchanged.",
                "File ▸ Export ▸ All Solver Inputs to Folder… (⌘E, moved from the fBNAsim export) gains a blocking-convention choice for finite-buffer networks — the same one as the SRBM export sheet and Qnet --export-cmp --loss-fix / --bas-fix — so the folder holds exactly what the command line produces.",
                "Release Notes keeps its Copy button in a pinned bar above the scrolling notes, and the tab bar's '+' is labelled 'New Network (⌘N)' to match the File menu.",
                "Menu bar reorganised into the standard macOS order — File · Edit · View · Network · Tools · Run · Test · Window · Help — with HIG naming and ellipsis discipline throughout.",
                "Renamed for the platform: 'Load Network…' to 'Open…', 'Load Example…' to 'Open Example…', 'New Tab' to 'New Network', 'Close' to 'Close Tab', 'Close All' to 'Close All Tabs', 'Network Primitives' to 'Show Network Primitives', 'Palette' to 'Tools', 'Changelog…' to 'Release Notes'.",
                "Commands moved to the menu that owns them: Select All from View to Edit, Straighten Network to the Network menu, and 'Fit Network to Window' became View ▸ Zoom to Fit with Zoom to Selection beside it. Clear Canvas… now asks for confirmation.",
                "Edit ▸ Find… is titled for what ⌘F will actually do: 'Find Node…', 'Find in Shell…' when the Shell has focus, 'Search Status Log…', or 'Search Help…' / 'Search Settings…' when one of those windows is key.",
                "One coherent shortcut map with every collision removed: ⇧⌘S was shared by Save As… and Run Spectral, ⌘1 by Zoom to 100 % and the Pointer tool, ⌘2 by Zoom to Fit Selection and the Multi-Select tool, and ⌘0 Reset Zoom duplicated ⌘1 Zoom to 100 % (now one ⌘0 Actual Size).",
                "The map is checked, not claimed: QNET_MENU_AUDIT=1 walks the built menu bar, prints every key equivalent and exits non-zero on a duplicate; a debug build asserts on one shortly after launch. Help ▸ Keyboard Shortcuts prints the same walk for users.",
                "Menu items observe the active editor, so they enable and disable live: every Run / Export / Analyze / Primitives item is disabled on an empty canvas, and the Run menu's Infinite- and Finite-Buffer sections are disabled for the other buffer mode — replacing eleven 'only for…' alerts.",
                "Undo / Redo follow canUndo / canRedo; Cut / Copy / Duplicate / Delete follow the selection while still forwarding to a focused text field; Delete Selected Link needs a selected link; Test items are disabled while a sweep is running instead of showing an 'already running' alert.",
                "Run menu exposes three commands that were previously reachable only through the AI assistant: Run Exact Simulation, Run Linear Program and Run Multi-Class SRBM.",
                "⌘W closes the front auxiliary window (About, Qnet Help, Release Notes, Settings) when one is in front, and closes the active tab only when the canvas window is key. File ▸ Close Window (⇧⌘W) and File ▸ Open Recent (with Clear Menu, fed by every open and save) were added.",
                "Window ▸ Show Next Tab / Show Previous Tab rotate the canvas tabs; About, Help and Release Notes close on Escape and are listed in the Window menu; native window tabbing is disabled so ⌘T cannot merge them into the canvas window.",
                "Help ▸ Qnet Help (⌘?) opens a single searchable, typeset help window: a sidebar of topics grouped Concepts / Infinite-Buffer Methods / Finite-Buffer Methods / Workflows / AI Providers, a search field that filters on titles and body text, and a detail pane typeset at a readable measure.",
                "About Qnet is a proper Mac About panel: app icon (SF Symbol fallback when running unbundled), version with the full build identifier and a 'Built <date> at <time>' line, one-line description, copyright, and Release Notes / Acknowledgements links.",
                "Export menu consolidated to solver-named commands: 'Finite Simulator Input (fBNAsim)…', 'SRBM Solver Input (.in)…', 'QNA Input (.qna)…' and 'All Solver Inputs to Folder…'. Three identical SRBM export commands were merged; output files are unchanged, and every save panel proposes the document's name.",
                "Generate Random Network and Find Node are grouped SwiftUI sheets with steppers, menu pickers and inline validation. Test-set sheets gained Escape-to-cancel and the '# test cases' row is labelled 'Test cases'.",
                "Shell scrollback is captured as the raw byte stream the child shell emits (capped at 1 MiB) and replayed on the next launch, so the previous session's output round-trips exactly, colours and all — the old character-grid snapshot lost colour, lines past the cap and output from vim or less.",
                "A safety reset is fed between the replayed bytes and the new-session separator, so a prior session killed mid-vim or mid-paste cannot strand the new shell in alt-screen mode.",
                "Shell scrollback is saved consistently across quits: the transcript is written unconditionally before any tab logic runs, 'Don't Restore' for tabs no longer wipes shell history, and the periodic backstop save dropped from 60 s to 10 s so a force-quit loses only the last few seconds.",
                "Status pane gained a Clear All button; the cleared history really does not come back on the next launch.",
                "Restored shell scrollback no longer shows 35 blank rows between the 'previous session above' separator and the new prompt, and the restored history actually appears — zsh's PROMPT_SP erase, which had wiped the replayed rows, is scrolled past before the shell starts.",
                "Status pane and shell scrollback visibly restore on relaunch: the Status pane scrolls to its newest message, restored entries are followed by a dated 'New session' separator, status writes trigger debounced saves so the log is crash-safe, and the shell transcript is snapshotted periodically.",
                "version_patch.txt — the persistent build counter — is no longer deleted by ship_prep.sh and clean_build.sh, so a clean rebuild keeps its patch number; and the in-development changelog entry's version tracks AppVersion live, so About and Release Notes always match the running binary.",
                "Added clean_build.sh (the recommended clean compile after moving the tree between Macs via Dropbox) and ship_prep.sh (wipes regenerable build outputs and zips the cleaned tree into ../Qnet.bak.<timestamp>.zip).",
                "Individual algorithm runs print performance measures in the same vertical metric-per-row layout as Run Comparison, instead of a station-major table that ran off the right edge on networks with many stations.",
                "Fixed an exporter bug where a source with split routing into several entry stations was collapsed onto whichever station its first link pointed at, saturating one station in the simulator while the analytical methods saw the split. Each (source, entry station) pair is now its own simulator class.",
                "Fixed fBNAsim's Poisson sampler: 'poisson lambda=L' had returned a Poisson count and used it as an inter-arrival delay, inverting the rate. It now draws Exp(L) inter-arrivals, so utilisations and queue lengths on Poisson-source networks match the analytical methods.",
                "Fixed editing a node's parameters a second time appearing to revert to the values on disk: every parameter change now writes a per-tab snapshot that the editor overlays before presenting the sheet.",
                "Added fBNActmc, an exact CTMC reference solver (Python) for 2-station M/M/1 tandems with finite buffers in Loss and BAS+ext-loss modes; fBNAsim BAS+ext-loss matches it to 4 decimal places across K = 2..10.",
                "Fixed an off-by-one in NetworkExporter — buffer_sizes is emitted verbatim, so the simulator's total capacity matches what SRBM / FEM / LP model.",
                "Run Comparison's default blocking regime is BAS + External Loss (previously Loss); the popup labels it 'recommended' and the text explains that it matches the SRBM convention.",
                "Run Comparison's banner reports the heavy-traffic buffer-scaling diagnostic K·(1−ρ) per station: below 1 at a busy station the SRBM limit is loose; above 10 the buffer is effectively infinite.",
                "Added Tandem2.MM1.K5.fin.bnet (small-K pressure test against fBNActmc), ShenChenDaiDai02.d2.c1.1.fin.bnet (2-station analogue of the 3D variant 1) and MM1K.d1.c1.fin.bnet (M/M/1/K=11 with closed-form answers).",
                "Renamed the Swift target and source folder from BNETGUI to QnetGUI, then to Qnet, so the build artifact and process name match the app.",
                "Added pane corner resize: drag where panes meet to move both dividers at once.",
                "Added fBNAlp, a finite-buffer LP solver for the SRBM in a d-dimensional rectangle, with its own Run item; Run Comparison for finite networks runs it alongside spectral, FEM and Monte Carlo, and it reports ρ, Γ and sojourn per station.",
                "Fixed a fBNAlp accuracy bug — upper-face reflection coefficients were dropping off-diagonal terms — and switched HiGHS to interior-point with a time limit; mean queue lengths now match the spectral solver within 0.1 percent.",
                "Brought the BNAlp and BNAmc source trees in-tree so Qnet builds without external symlinks; the default LP backend is HiGHS.",
                "Run Comparison tables print every value with exactly 7 digits regardless of magnitude, so columns line up across rows of different scales.",
                "Fixed an off-by-one in the SRBM exporter — per-station capacity now includes the in-service slot, matching the simulator.",
                "Added the Qnet --export-cmp <bnet> <outdir> CLI mode that writes every solver's input file so the solvers can be invoked directly.",
            ]
        ),
        Entry(
            version: "0.90.01",
            timestamp: "04.26.2026.1647",  // freeze: this entry shipped with that build
            notes: [
                "Renamed the application from BNET to Qnet (visible name and bundle). "
                + "The internal Swift target, Keychain identifier, and source layout "
                + "are unchanged so existing API keys and project files still work.",

                "Introduced version tracking. Every build_app.sh run bumps the patch "
                + "number and stamps the build's MM.DD.YYYY.HHMM timestamp into "
                + "AppVersion.swift; the About Qnet window and this changelog show "
                + "the full identifier (version.MM.DD.YYYY.HHMM).",

                "Run Comparison: rebuilt the column-alignment logic. The awk script "
                + "now computes per-column widths dynamically and pads with consistent "
                + "spacing, so headers always line up over their values regardless of "
                + "value length. Shortened 'Spectral Method' to 'Spectral' in the "
                + "comparison header.",

                "Run Comparison: added a one-line load banner above the comparison "
                + "table (\"Network load: rho_max = X.XX at Sk\") with a regime note. "
                + "When rho_max < 0.85 the banner warns that SRBM/FEM are heavy-traffic "
                + "limits and deviation from simulation is expected.",

                "Simulator: fixed a topology bug where every external arrival was "
                + "hard-coded to enter station 0 regardless of which source it came "
                + "from. Each source now feeds its actual downstream station, "
                + "matching what SRBM/FEM have always assumed. Single-source / "
                + "S1-only networks are unaffected.",

                "Simulator: the per-class outside queue (manufacturing blocking) is "
                + "now per-class instead of a single shared FIFO. A class whose entry "
                + "station is full no longer blocks other classes whose entry "
                + "stations have space.",

                "Simulator output convention: E[X_k] and sojourn_k now report TOTAL "
                + "station occupancy (buffer + customer in service) and TOTAL time at "
                + "station, matching the SRBM/FEM convention from Dai-Harrison "
                + "heavy-traffic theory. Previously the simulator printed buffer-only "
                + "occupancy and queue-wait sojourn, which silently differed from "
                + "the analytical methods by Σρ_i. Per-station E[X_k] sum now equals "
                + "per-class N_total sum (mass conservation).",

                "Simulator and analytical methods: corrected the inline semantics "
                + "comments in stats.c, srbm_solver.c, and bna_fm_gauss.c so future "
                + "readers know that x_k counts the in-service customer.",

                "GUI: the application Help menu now leads with this Changelog item, "
                + "and the macOS About menu now opens a custom \"About Qnet\" window "
                + "showing the full version identifier."
            ]
        )
    ]

    /// Sanity check: returns true when the topmost entry is the live
    /// in-development one (timestamp == nil, label tracks AppVersion
    /// automatically). Returns false only if someone froze the top
    /// entry without prepending a new in-development entry above it,
    /// which means the running build has no changelog slot. The view
    /// flags that case in red so the developer notices before shipping.
    static var topEntryMatchesAppVersion: Bool {
        guard let top = entries.first else { return false }
        return top.timestamp == nil
    }
}

// The Release Notes window that renders these entries lives in
// ReleaseNotesWindow.swift (`ReleaseNotesView` / `ReleaseNotesWindow`).
